version: "3.8"

services:
  read_service:
    build:
      context: .
      dockerfile: Dockerfile.read
    ports:
      - "8000:8000"
    networks:
      - my_network

  calculate_service:
    build:
      context: .
      dockerfile: Dockerfile.calculate
    ports:
      - "8001:8001"
    depends_on:
      - read_service
    networks:
      - my_network

  generate_service:
    build:
      context: .
      dockerfile: Dockerfile.generate
    ports:
      - "8002:8002"
    depends_on:
      - calculate_service
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

